### ISSUE TITLE
Module Relations associate button and record disappear after making second module relation

### ISSUE THREAD

**Issue by jitenders859** [davidjconnelly/trongate-framework#60] opened 2021-08-04 07:39 UTC
![Associated2](https://user-images.githubusercontent.com/41188075/128140885-27314750-937f-4ec5-a430-3a01b281f4d9.png)
![associated](https://user-images.githubusercontent.com/41188075/128140897-fc7e2e22-e9a8-4201-986e-25ab9b5fb563.png)

I have created many to many relation with store item colors was working fine but  after creating second many to many relations with store item sizes . Associated store item colors box content not showing

**Comment by StephenMM1952** [comment] 2021-08-05 10:33
I think the problem is caused by using the "window.onload = function ()" for each summary panel. I'm not sure why yet but when I edited the summary_panel.php script for the item_sizes relationship (the second summary panel) as follows 

`<script>
    window.onload = function() {
        fetchAssociatedRecords('<?= $relation_name ?>', '<?= $update_id ?>');
        fetchAssociatedRecords('associated_store_items_and_store_item_colours', '1');
    }
</script>`

both panels were populated  and worked ok. Probably needs an array of function calls to be called at the bottom of the html

**Comment by StephenMM1952** [comment] 2021-08-05 10:45
The solution is to replace window.onload with window.addEventListener as follows:

`<script>
    // window.onload = function() {
    //     fetchAssociatedRecords('<?= $relation_name ?>', '<?= $update_id ?>');
    // }

    window.addEventListener('load', function() {
            fetchAssociatedRecords('<?= $relation_name ?>', '<?= $update_id ?>');})
</script>`

**Comment by jitenders859** [comment] 2021-08-05 12:01
Thanks @StephenMM1952  working now.

**Comment by davidjconnelly** [comment] 2021-08-09 12:00
This is now fixed.  Many thanks to StephenMM1952 for helping with that.  Super grateful vibes.  Thank you!

**Closed by davidjconnelly** 2021-08-09 12:00 UTC
