### ISSUE TITLE
Expected type ( Not sure this is a problem :D )

### ISSUE THREAD

**Issue by CRX3** [davidjconnelly/trongate-framework#34] opened 2021-06-15 21:34 UTC
engine > Image.php
	line 72, 75, 76, 101, 104, 105, 106, 120, 128, 197, 213, 226, 281, 310
	$this->image : Expected type ‘GdImage’ found ‘resource’

**Comment by davidjconnelly** [comment] 2021-06-16 16:01
Hi.  I'm not entirely sure about this one.  The image.php file was was written by my friend Derek.  I'll ask him to have a look at this tomorrow.  In the meantime, if you have any more info then I'd be grateful.  Cheers.

**Comment by delboy1978uk** [comment] 2021-06-17 14:43
Did you load the image first? 

```php
$image = new Image('/path/to/my.jpg');

// Or...
$image = new Image();
$image->load('/path/to/my.png');
```

**Comment by delboy1978uk** [comment] 2021-06-17 16:33
Oh, actually, you do have a resource, so, are you running on PHP 8? I can guarantee that class up until 7.4 (the code is from an earlier version of https://github.com/delboy1978uk/image/), but I haven't tested it on PHP8 yet, I was was waiting  on Travis CI updating, but I guess that's happened now, I might look at it tonight

**Comment by delboy1978uk** [comment] 2021-06-17 17:20
It works fine and I tested it on PHP8, and there is nothing in this older version that is all that different (all i did in my latest version was put jpeg functions in a jpeg class, png functions in a png class, etc), can you tell me what you are trying to do with it and maybe share some code?

**Comment by delboy1978uk** [comment] 2021-06-17 17:44
Yes this is a new type of class as of PHP 8.0.0 https://www.php.net/manual/en/class.gdimage, but I'm wondering why I haven't been able to reproduce your issue, what is expecting one of those?

**Comment by davidjconnelly** [comment] 2021-06-17 17:47
Thanks, Derek.

**Comment by davidjconnelly** [comment] 2021-06-17 17:48
If we cannot reproduce the fault then the only options I can think of are to either close this one or leave it hanging in the hope that somebody else has something for us.

Any advice?

**Comment by delboy1978uk** [comment] 2021-06-17 17:51
Wait for his reply, if there's something I need to update on my own lib to be properly php 8 (and php8 apparently replaces a 'resource' as a 'GdImage'), then I'll obviously do so, and send you a PR on your own code

**Comment by delboy1978uk** [comment] 2021-06-17 18:08
@davidjconnelly, if you look to the right you will see that you  can tag issues with a label, such as 'improvement', or 'bug', it can help you  manage issues as they come in,  for example  once our man  here shows me how to reproduce the bug you can tag it with  a bug label, and then its a real 'deal with this' issue

**Comment by DaFa66** [comment] 2021-06-18 04:08
Hi guys, I've noticed the gd extension in PHP 8 is not being loaded by default.  Could this be the issue?  Easy to see, just open a terminal/ command prompt and enter php -m to list all loaded extensions (as long as php is in the system path).  If you don't see the gd module in the list you know the picture functions in Trongate won't work.  Then it's just a matter of editing the php.ini file to include this library, then restart the server to enable it and all should work as expected.

**Comment by delboy1978uk** [comment] 2021-06-18 09:15
That will indeed be the problem!  Easy fix thankfully. Funny, as I had to contact Fasthosts the other day for a client of mine, Fasthosts didnt have gd on their PHP 7.4, so everything crashed the second you tried to call a gd function. I had to explain to their engineers what they had done wrong! Took about 5 days for them to sort it out lol

**Comment by delboy1978uk** [comment] 2021-06-18 12:53
I should mention however that depending how your PHP is set up, you might have an ini for the CLI, so `php -m` could give you different results than `phpinfo()`, so check that way also.

**Comment by DaFa66** [comment] 2021-06-18 16:06
Good point 👍

**Comment by davidjconnelly** [comment] 2021-06-19 16:00
I'm getting the feeling that this might be one for the soon-to-open discussion forum at trongate.io.  Is that agreeable?

**Comment by DaFa66** [comment] 2021-06-19 23:04
This topic has already been discussed on the SCA forum and sorted. By all
means we can discuss again on the new Trongate.io forum 👍

**Comment by DaFa66** [comment] 2021-06-19 23:12
Here is the link to the SCA forum fix
https://ums.myds.me/phpbb/viewtopic.php?t=856

**Comment by davidjconnelly** [comment] 2021-06-20 17:16
I had assumed the SCA forum to be closed to the general public.  Anyway, I'll close this one.  Thanks.

**Closed by davidjconnelly** 2021-06-20 17:16 UTC

**Comment by delboy1978uk** [comment] 2021-06-21 12:20
@DaFa66 I don't have access to that forum, can you share whatever change was suggested?

**Comment by DaFa66** [comment] 2021-06-21 12:25
Same suggestion as here but more in depth with examples on how to edit the php.ini to enable the GD module.

If you want access to the forum, just create an account and I'll activate 👍
